# Generated by Django 2.2.2 on 2019-07-03 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dk_dropbox', '0002_userdropboxhistory_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdropboxhistory',
            old_name='user_id',
            new_name='dk_user',
        ),
    ]
