# Generated by Django 2.2.2 on 2019-07-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dk_dropbox', '0003_auto_20190703_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdropboxhistory',
            name='dp_file_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
